# -*- coding: utf-8 -*-
"""CarSalesDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTCSsMzd8Mji9diFj1TDMYwaGCKyrcYU
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

st.set_page_config(
    page_title="Car Sales Executive Dashboard",
    page_icon="🚗",
    layout="wide",
)

# ---------- DATA LOADING ----------
st.sidebar.subheader("Data source")

uploaded_file = st.sidebar.file_uploader("Upload car sales CSV", type=["csv"])

@st.cache_data
def load_car_data(file):
    if file is not None:
        df = pd.read_csv(file)
    else:
        df = pd.read_csv("Car_sales.csv")  # fallback default dataset [file:74]

    df.columns = [c.strip() for c in df.columns]

    df = df.rename(
        columns={
            "Sales in thousands": "SalesK",
            "4-year resale value": "Resale4Y",
            "Vehicle type": "VehicleType",
            "Price in thousands": "PriceK",
            "Engine size": "EngineSize",
            "Wheelbase": "Wheelbase",
            "Curb weight": "CurbWeight",
            "Fuel capacity": "FuelCap",
            "Fuel efficiency": "MPG",
        }
    )

    num_cols = ["SalesK", "Resale4Y", "PriceK", "EngineSize", "Horsepower",
                "Wheelbase", "Width", "Length", "CurbWeight", "FuelCap", "MPG"]
    for c in num_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    df["Latest Launch"] = pd.to_datetime(df["Latest Launch"], errors="coerce", format="%d-%b-%y")
    return df

df = load_car_data(uploaded_file)

# ---------- SIDEBAR FILTERS ----------
st.sidebar.title("Filters")

manufacturers = sorted(df["Manufacturer"].str.strip().unique().tolist())
vehicle_types = sorted(df["VehicleType"].dropna().unique().tolist())

sel_makers = st.sidebar.multiselect("Manufacturer", manufacturers, default=manufacturers[:8])
sel_types = st.sidebar.multiselect("Vehicle type", vehicle_types, default=vehicle_types)

price_min, price_max = float(df["PriceK"].min()), float(df["PriceK"].max())
sel_price = st.sidebar.slider("Price range (thousands)", price_min, price_max,
                              (price_min, price_max))

# Apply filters
mask = df["Manufacturer"].str.strip().isin(sel_makers)
mask &= df["VehicleType"].isin(sel_types)
mask &= df["PriceK"].between(sel_price[0], sel_price[1])
filtered = df[mask]

# ---------- HEADER ----------
st.markdown("## Car Sales – Executive Analytics Dashboard")
st.caption("Dataset: Manufacturer, model, sales, price, specs, fuel efficiency, and launch date. [file:74]")

# ---------- KPI CARDS ----------
total_models = filtered["Model"].nunique()
total_sales = filtered["SalesK"].sum()
avg_price = filtered["PriceK"].mean()
avg_mpg = filtered["MPG"].mean()

col1, col2, col3, col4 = st.columns(4)
col1.metric("Models", f"{total_models}")
col2.metric("Total Sales", f"{total_sales:,.1f} K units")
col3.metric("Avg Price", f"${avg_price:,.1f} K")
col4.metric("Avg Fuel Efficiency", f"{avg_mpg:,.1f} MPG")

# ---------- TABS ----------
tab_overview, tab_brand, tab_specs, tab_raw = st.tabs(
    ["Overview", "Brand performance", "Specs & efficiency", "Raw data"]
)

# ===== OVERVIEW TAB =====
with tab_overview:
    c1, c2 = st.columns(2)

    # Sales vs Price scatter
    with c1:
        st.subheader("Sales vs Price")
        fig_scatter = px.scatter(
            filtered,
            x="PriceK",
            y="SalesK",
            color="Manufacturer",
            hover_data=["Model", "VehicleType"],
            size="SalesK",
            template="plotly_dark",
        )
        fig_scatter.update_layout(height=400)
        st.plotly_chart(fig_scatter, use_container_width=True)

    # Sales by vehicle type
    with c2:
        st.subheader("Sales by vehicle type")
        type_sales = filtered.groupby("VehicleType", as_index=False)["SalesK"].sum()
        fig_type = px.pie(
            type_sales,
            names="VehicleType",
            values="SalesK",
            hole=0.4,
            template="plotly_dark",
        )
        st.plotly_chart(fig_type, use_container_width=True)

    st.subheader("Top 10 models by sales")
    top_models = filtered.nlargest(10, "SalesK")[["Manufacturer", "Model", "SalesK", "PriceK", "MPG"]]
    st.dataframe(top_models.style.format({"SalesK": "{:,.1f}", "PriceK": "{:,.1f}", "MPG": "{:,.1f}"}),
                 use_container_width=True)

# ===== BRAND PERFORMANCE TAB =====
with tab_brand:
    st.subheader("Brand performance snapshot")

    brand_sales = filtered.groupby("Manufacturer", as_index=False).agg(
        TotalSales=("SalesK", "sum"),
        AvgPrice=("PriceK", "mean"),
        AvgResale=("Resale4Y", "mean"),
    )

    fig_brand = px.bar(
        brand_sales.sort_values("TotalSales", ascending=False).head(15),
        x="Manufacturer",
        y="TotalSales",
        hover_data=["AvgPrice", "AvgResale"],
        template="plotly_dark",
        labels={"TotalSales": "Sales (thousands)"},
        title="Top manufacturers by sales",
    )
    st.plotly_chart(fig_brand, use_container_width=True)

    # Resale vs Price
    st.subheader("Price vs 4-year resale value")
    fig_resale = px.scatter(
        filtered,
        x="PriceK",
        y="Resale4Y",
        color="Manufacturer",
        hover_data=["Model"],
        trendline="ols",
        template="plotly_dark",
        labels={"PriceK": "Price (thousands)", "Resale4Y": "4-year resale (thousands)"},
    )
    st.plotly_chart(fig_resale, use_container_width=True)

# ===== SPECS & EFFICIENCY TAB =====
with tab_specs:
    st.subheader("Engine size vs fuel efficiency")

    fig_engine = px.scatter(
        filtered,
        x="EngineSize",
        y="MPG",
        color="VehicleType",
        hover_data=["Manufacturer", "Model", "Horsepower"],
        template="plotly_dark",
        labels={"EngineSize": "Engine size (L)", "MPG": "Fuel efficiency (MPG)"},
    )
    st.plotly_chart(fig_engine, use_container_width=True)

    c3, c4 = st.columns(2)

    with c3:
        st.subheader("Horsepower distribution")
        fig_hp = px.histogram(
            filtered,
            x="Horsepower",
            nbins=25,
            color="VehicleType",
            template="plotly_dark",
        )
        st.plotly_chart(fig_hp, use_container_width=True)

    with c4:
        st.subheader("Launch timeline")
        timeline = filtered.dropna(subset=["Latest Launch"]).sort_values("Latest Launch")
        fig_time = px.scatter(
            timeline,
            x="Latest Launch",
            y="SalesK",
            color="Manufacturer",
            hover_data=["Model", "PriceK"],
            template="plotly_dark",
        )
        st.plotly_chart(fig_time, use_container_width=True)

# ===== RAW DATA TAB =====
with tab_raw:
    st.subheader("Filtered dataset")
    st.dataframe(filtered, use_container_width=True)